[package]
name = "api-client"
version = "0.1.0"
authors = ["John Peel <john@dgby.org>"]
edition = "2021"
repository = "https://github.com/JohnPeel/api-client/"
documentation = "https://johnpeel.github.io/api-client/api_client/"
license = "MIT"
readme = "README.md"

[dependencies]
async-trait = "0.1"
bytes = "1.2"
reqwest = { version = "0.11", default-features = false, features = ["json"] }
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
reqwest = { version = "0.11", default-features = false, features = ["rustls-tls", "json"] }
tokio-test = "0.4"
